name: DeforaOS C CI (ubuntu-latest)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: initialize sub-modules
      run: git submodule init
    - name: update sub-modules
      run: git submodule update
    - name: bootstrap libSystem
      run: git clone https://github.com/DeforaOS/libSystem.git libSystem && for dir in include data src; do (cd libSystem/$dir && make PREFIX="$HOME/opt/DeforaOS" install); done
    - name: bootstrap configure
      run: git clone https://github.com/DeforaOS/configure.git configure && (cd configure/src && PKG_CONFIG_PATH="$HOME/opt/DeforaOS/lib/pkgconfig" make PREFIX="$HOME/opt/DeforaOS" install)
    - name: configure
      run: $HOME/opt/DeforaOS/bin/configure -p "$HOME/opt/DeforaOS" -M i386-debug
    - name: make (i386)
      run: PKG_CONFIG_PATH="$HOME/opt/DeforaOS/lib/pkgconfig" make ARCH="i386" CCSHARED="cc -shared"
    - name: make tests (i386)
      run: PKG_CONFIG_PATH="$HOME/opt/DeforaOS/lib/pkgconfig" make ARCH="i386" CCSHARED="cc -shared" tests
    - name: make distcheck (i386)
      run: PKG_CONFIG_PATH="$HOME/opt/DeforaOS/lib/pkgconfig" make ARCH="i386" CCSHARED="cc -shared" distcheck
